<?php print $content; ?>
<?php 
	global $user;
	if($user->uid == 1 || in_array('Admin Users', $user->roles)) { ?>

<?php
	//blocks generated by the view module don't need edit links
	//this keeps an orphaned 'edit block' link from appearing on every page due to the sidebar image view
	
	if($block->module == 'block') {
	$thisurl = "http://" .$_SERVER['HTTP_HOST'] .$_SERVER['REQUEST_URI'];
	global $base_url;
?>
	<a style="float:right" href="<?php echo $base_url; ?>/admin/build/block/configure/<?php echo $block->module; ?>/<?php echo $block->delta; ?>">Edit Block</a>
<?php
	}
?>

<?php } ?>